import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Контент 3',
  description: 'Generated by create next app',
}

export default function GeneralInfo() {
  return (
    <div className='content'>
      <section>
          <div className='container'>
            3
          </div>
      </section>
    </div>
  )
  }
  