import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Авторизация',
  description: 'Generated by create next app',
}

export default function GeneralInfo() {
    return (
      <div className='content'>
        <section>
          <div className='container'>
            123
          </div>
        </section>
      </div>
    )
  }
  