import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Авторизация',
  description: 'Generated by create next app',
}

export default function GeneralInfo() {
    return (
      <main>
        Войти
      </main>
    )
  }
  