import type { Metadata } from 'next'
import Image from 'next/image'
import photo_1 from '@/public/img/sections/tsc/photo_1.jpg';
import photo_2 from '@/public/img/sections/tsc/photo_2.jpg';
import photo_3 from '@/public/img/sections/tsc/photo_3.jpg';
import photo_4 from '@/public/img/sections/tsc/photo_4.jpg';
import photo_5 from '@/public/img/sections/tsc/photo_5.jpg';
import photo_6 from '@/public/img/sections/tsc/photo_6.jpg';
import photo_7 from '@/public/img/sections/tsc/photo_7.jpg';
import photo_8 from '@/public/img/sections/tsc/photo_8.jpg';
import photo_9 from '@/public/img/sections/tsc/photo_9.jpg';
import photo_10 from '@/public/img/sections/tsc/photo_10.jpg';
import photo_11 from '@/public/img/sections/tsc/photo_11.jpg';
import photo_12 from '@/public/img/sections/tsc/photo_12.jpg';
import photo_13 from '@/public/img/sections/tsc/photo_13.jpg';
import photo_14 from '@/public/img/sections/tsc/photo_14.jpg';
import photo_15 from '@/public/img/sections/tsc/photo_15.jpg';
import photo_16 from '@/public/img/sections/tsc/photo_16.jpg';
import photo_17 from '@/public/img/sections/tsc/photo_17.jpg';
import photo_18 from '@/public/img/sections/tsc/photo_18.jpg';
import photo_19 from '@/public/img/sections/tsc/photo_19.jpg';
import photo_20 from '@/public/img/sections/tsc/photo_20.jpg';
import photo_21 from '@/public/img/sections/tsc/photo_21.jpg';
import photo_22 from '@/public/img/sections/tsc/photo_22.jpg';
import photo_23 from '@/public/img/sections/tsc/photo_23.jpg';
import photo_24 from '@/public/img/sections/tsc/photo_24.jpg';
import photo_25 from '@/public/img/sections/tsc/photo_25.jpg';
import photo_26 from '@/public/img/sections/tsc/photo_26.jpg';
import photo_27 from '@/public/img/sections/tsc/photo_27.jpg';

export const metadata: Metadata = {
  title: 'ТСЦ',
  description: 'Generated by create next app',
}

export default function GenerlInfo() {
    return (
      <>
      <h1>ТСЦ</h1>
        <div className='text_center img-w50'>
          <Image src={photo_1} alt="Shadow" loading="lazy" />
          <Image src={photo_2} alt="Shadow" loading="lazy" />
          <Image src={photo_3} alt="Shadow" loading="lazy" />
          <Image src={photo_4} alt="Shadow" loading="lazy" />
          <Image src={photo_5} alt="Shadow" loading="lazy" />
          <Image src={photo_6} alt="Shadow" loading="lazy" />
          <Image src={photo_7} alt="Shadow" loading="lazy" />
          <Image src={photo_8} alt="Shadow" loading="lazy" />
          <Image src={photo_9} alt="Shadow" loading="lazy" />
          <Image src={photo_10} alt="Shadow" loading="lazy" />
          <Image src={photo_11} alt="Shadow" loading="lazy" />
          <Image src={photo_12} alt="Shadow" loading="lazy" />
          <Image src={photo_13} alt="Shadow" loading="lazy" />
          <Image src={photo_14} alt="Shadow" loading="lazy" />
          <Image src={photo_15} alt="Shadow" loading="lazy" />
          <Image src={photo_16} alt="Shadow" loading="lazy" />
          <Image src={photo_17} alt="Shadow" loading="lazy" />
          <Image src={photo_18} alt="Shadow" loading="lazy" />
          <Image src={photo_19} alt="Shadow" loading="lazy" />
          <Image src={photo_20} alt="Shadow" loading="lazy" />
          <Image src={photo_21} alt="Shadow" loading="lazy" />
          <Image src={photo_22} alt="Shadow" loading="lazy" />
          <Image src={photo_23} alt="Shadow" loading="lazy" />
          <Image src={photo_24} alt="Shadow" loading="lazy" />
          <Image src={photo_25} alt="Shadow" loading="lazy" />
          <Image src={photo_26} alt="Shadow" loading="lazy" />
          <Image src={photo_27} alt="Shadow" loading="lazy" />
        </div>
      </>
    )
  }
  